trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
      - release*
  paths:
    exclude:
      - README.md

stages:
- stage: Preflight
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-22.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js'

      - script: |
          npm i -g npm
          npm install
        displayName: 'npm install and build'

      - script: |
          npm run standard
        displayName: 'Standardjs report'

      - script: |
          npm audit --production
        displayName: Check for vulnerabilities
- stage: Test
  jobs:
  - template: azure-templates/test.yml
    parameters:
      nodeVersion: '16'
  - template: azure-templates/test.yml
    parameters:
      nodeVersion: '17'
  - template: azure-templates/test.yml
    parameters:
      nodeVersion: '18'
